mybooksproject/mybooksapp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name='mybooksapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:booklist_id>/', views.detail_list, name='detail_list'),
    path('detail_genre/<int:bookgenre_id>/', views.detail_genre, name='detail_genre'),
    path('detail_book/<int:book_id>/', views.detail_book, name='detail_book'),
    path('new_book/', views.new_book, name='new_book'),
    path('delete_book/<int:book_id>/', views.delete_book, name='delete_book'),
    path('update_book/<int:book_id>', views.update_book, name='update_book'),
]

mybooksproject/mybooksproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mybooksapp/', include('mybooksapp.urls'))
]

mybooksproject/mybooksapp/models.py
from django.db import models

# Create your models here.

class BookList(models.Model):
    name = models.CharField(max_length=50)
    icon = models.CharField(max_length=100, default=True)

    def __str__(self):
            return f'{self.name}'

class BookGenre(models.Model):
    name = models.CharField(max_length=50)
    icon = models.CharField(max_length=100, default=True)

    def __str__(self):
            return f'{self.name}'

class Book(models.Model):
    title = models.CharField(max_length=50)
    author = models.CharField(max_length=50)
    content = models.CharField(max_length=1500)
    rating = models.IntegerField(default=0, null=False)
    done = models.BooleanField(default=False, null=False)
    price = models.DecimalField(max_digits=7, decimal_places=2, default=0.00, null=False)
    cover = models.CharField(max_length=200)
    booklist = models.ForeignKey(BookList, on_delete=models.CASCADE)
    genre = models.ForeignKey(BookGenre, on_delete=models.CASCADE)

    def __str__(self):
            return f'{self.title} {self.author} {self.content} {self.rating} {self.done} {self.price} {self.cover} {self.booklist} {self.genre}'

mybooksproject/mybooksapp/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import BookList, BookGenre, Book
import json
import requests

def index(request):
    listen = BookList.objects.all()
    return render(request, 'mybooksapp/index.html', {'listen':listen})

def detail_list(request, booklist_id):
    liste = get_object_or_404(BookList, pk=booklist_id)
    genres = BookGenre.objects.all()
    return render(request, 'mybooksapp/detail_list.html', {'liste':liste, 'genres':genres})

def detail_genre(request, bookgenre_id):
    genre = get_object_or_404(BookGenre, pk=bookgenre_id)
    books = Book.objects.filter(genre=bookgenre_id)
    return render(request, 'mybooksapp/detail_genre.html', {'genre':genre, 'books':books})

def detail_book(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    return render(request, 'mybooksapp/detail_book.html', {'book':book})

def new_book(request):
    if "isbn" in request.POST:
       

        user_agent = 'JSONImporter/0.1 (https://beep.boop.com/; notgonna@say.it); Python/3.8.5'
        headers = {'User-Agent': user_agent, 'Accept': 'text/json'}

        isbn_str = request.POST["isbn"]

        url = "https://www.googleapis.com/books/v1/volumes?q=isbn:" + isbn_str
        # url = "https://openlibrary.org/isbn/" + isbn_str
        response = requests.get(url,headers=headers)
        source = response.content


        data = json.loads(source)
        

        print(json.dumps(data, indent=2))
        
        title = data["items"][0]["volumeInfo"]["title"]
        author = data["items"][0]["volumeInfo"]["authors"]
        content = data["items"][0]["volumeInfo"]["description"]
        # rating = data["items"][0]["volumeInfo"]["title"]
        # price = data["items"][0]["volumeInfo"]["title"]
        cover = data["items"][0]["volumeInfo"]["imageLinks"]["thumbnail"]
        booklist = BookList.objects.get(pk=request.POST["booklist"])
        genre = BookGenre.objects.get(pk=request.POST["genre"])
        Book.objects.create(title=title,
                            author=author,
                            content=content,
                            # rating=rating,
                            # price=price,
                            cover=cover,
                            booklist=booklist,
                            genre=genre,)
        return HttpResponseRedirect(reverse('mybooksapp:detail_list', args=[booklist.id]))

    elif request.method == 'POST':
        title = request.POST["title"]
        author = request.POST["author"]
        content = request.POST["content"]
        rating = request.POST["rating"]
        price = request.POST["price"]
        cover = request.POST["cover"]
        booklist = BookList.objects.get(pk=request.POST["booklist"])
        genre = BookGenre.objects.get(pk=request.POST["genre"])
        Book.objects.create(title=title,
                            author=author,
                            content=content,
                            rating=rating,
                            price=price,
                            cover=cover,
                            booklist=booklist,
                            genre=genre,)
        return HttpResponseRedirect(reverse('mybooksapp:detail_list', args=[booklist.id]))

    return render(request, 'mybooksapp/new_book.html', {"booklists": BookList.objects.all(), "genres": BookGenre.objects.all()})

def delete_book(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    book.delete()
    return HttpResponseRedirect(reverse('mybooksapp:index'))

def update_book_def(book, post):
    if "book_title" in post:
        book.title = post["book_title"]
    if "book_author" in post:
        book.author = post["book_author"]
    if "book_content" in post:
        book.content = post["book_content"]    
    if "book_rating" in post:
        try:
            rating = int(post["book_rating"]) 
        except ValueError:
            rating = 0
        book.rating = rating
    book.done = "book_done" in post
    if "book_price" in post:
        try:
            price = float(post["book_price"]) 
        except ValueError:
            price = 0
        book.price = price
    if "book_cover" in post:
        book.cover = post["book_cover"]
    if "book_booklist" in post:
        book.booklist = get_object_or_404(BookList, pk=post["book_booklist"])
    if "book_genre" in post:
        book.genre = get_object_or_404(BookGenre, pk=post["book_genre"])
    book.save()


def update_book(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    if request.POST:
        update_book_def(book, request.POST)
        return HttpResponseRedirect(reverse('mybooksapp:detail_book', args=[book.id]))
    listen = BookList.objects.all()
    genres = BookGenre.objects.all()
    context = {
            "listen": listen, 
            "genres": genres, 
            "book": book, 
            }
    return render(request, "mybooksapp/update_book_def.html", context)

mybooksproject/mybooksapp/templates/mybooksapp/detail_book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'mybooksapp/style.css' %}">
    <title>{{book.title}}</title>
</head>
<body>

    <div class='row justify-content-md-center p-2 mt-5'>
    <div class="col-lg-10 p-4 bg-white rounded shadow-sm">    

        <div class='container d-flex'>
            <img src="{{book.cover}}" class="" alt="image">
            <div class='pl-4'>
                <h2>{{book.title}}</h2>
                <p>{{book.content}}</p>
                <p><b>Autor: </b>{{book.author}}</p>
                <p><b>Bewertung: </b>{{book.rating}}</p>
                <p><b>Gelesen: </b>{% if book.done == True %} Ja {% else %} Nein {% endif %}</p>
                <p><b>Preis: </b>{{book.price}}</p>
                <p><b>Genre: </b>{{book.genre}}</p>
                <div class='mt-4'>
                    <a href="{% url 'mybooksapp:update_book' book.id%}" class='btn'>Bearbeiten</a>
                    <a href="{% url 'mybooksapp:delete_book' book.id%}" class='btn'>Löschen</a>
                </div>
            </div>
        </div>
    
    </div>
    </div>

</body>
</html>

mybooksproject/mybooksapp/templates/mybooksapp/detail_genre.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    {% load static %}
    <link href="{% static 'mybooksapp/images' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'mybooksapp/style.css' %}">
    <title>{{liste.name}}</title>
</head>
<body>

    <div class="d-flex justify-content-center flex-wrap">
        {%for book in books%}
        <div class="container text-center" style="width: 13.9rem;">
            <div class="card m-3" style="width: 10rem;">
                <img src="{{book.cover}}" class="card-img-top" alt="image" height="250px">
            </div>
            <a href="{% url 'mybooksapp:detail_book' book.id%}" class="btn" style="width: 10rem;">Zum Buch</a>
        </div>
        {%endfor%}
    </div>

    <div class='mt-5'>
        <button type="button" class="btn"><a href="{% url 'mybooksapp:new_book' %}" class='text-light'>+ Neues Buch hinzufügen</a></button>
    </div>

</body>
</html>

mybooksproject/mybooksapp/templates/mybooksapp/detail_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    {% load static %}
    <link href="{% static 'mybooksapp/images' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'mybooksapp/style.css' %}">
    <title>{{liste.name}}</title>
</head>
<body>

    <div class='justify-content-md-center'>
    <div class="d-flex justify-content-center flex-wrap">

        {%for genre in genres%}
            <div class="p-4 m-3 bg-white rounded shadow-sm text-center">
                <img src="{% static genre.icon %}" alt="image"></br>
                <a href="{% url 'mybooksapp:detail_genre' genre.id%}" class="btn mt-1">{{ genre.name }}</a></br>
            </div>
        {%endfor%}

        <button type="button" class="btn"><a href="{% url 'mybooksapp:new_book' %}" class='text-light'>+ Neues Buch hinzufügen</a></button>

    </div>
    </div>
  
</body>
</html>

mybooksproject/mybooksapp/templates/mybooksapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    {% load static %}
    <link href="{% static 'mybooksapp/images' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'mybooksapp/style.css' %}">
    <title>MyBooks</title>
</head>
<body>

    <div class='row justify-content-md-center p-2 pt-5 mt-5'>
        {% for list in listen%}
            <a href="{% url 'mybooksapp:detail_list' list.id%}"><img src="{% static list.icon %}" alt="image"></a>
        {% endfor %}
    </div>

</body>
</html>

mybooksproject/mybooksapp/templates/mybooksapp/new_book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'mybooksapp/style.css' %}">
    <title>Neues Buch hinzufügen</title>
</head>
<body>

  <div class='row justify-content-md-center p-2 mt-5'>
  <div class="col-lg-10 p-4 bg-white rounded shadow-sm">

    <form action="" method="post">
    <div class="form-group">
      {% csrf_token %}
      <label>Titel</label>
      <input type="text" name="title"><br>

      <label>Autor:in</label>
      <input type="text" name="author"><br>

      <label>Inhalt</label>
      <input type="textarea" name="content"><br>

      <label>Bewertung</label>
      <input type="number" name="rating"><br>

      <label>Preis</label>
      <input type="number" step="0.01" name="price"><br>

      <label>Cover</label>
      <input type="text" name="cover"><br>

      <label>Bücherliste</label>
      <select name="booklist">
        {% for list in booklists %}
          <option value="{{list.id}}">{{list}}</option>
        {% endfor %}
      </select></br>

      <label>Genre</label>
      <select name="genre">
        {% for genre in genres %}
          <option value="{{genre.id}}">{{genre}}</option>
        {% endfor %}
      </select></br>

      <div class="input-group">
        <input class="btn" type="submit" value="Speichern">
      </div>

    </div>
    </form>
    <form action="" method="post">
    <div class="form-group">
      {% csrf_token %}
      <label>Oder gib eine ISBN ein und lasse dein Regal automatisch auffüllen</label>
      <input type="number" name="isbn"><br>
      <label>Bücherliste</label>
      <select name="booklist">
        {% for list in booklists %}
          <option value="{{list.id}}">{{list}}</option>
        {% endfor %}
      </select></br>

      <label>Genre</label>
      <select name="genre">
        {% for genre in genres %}
          <option value="{{genre.id}}">{{genre}}</option>
        {% endfor %}
      </select></br>
      <div class="input-group">
        <input class="btn" type="submit" value="Speichern">
      </div>

    </div>
    </form>
  </div>
  </div>

</body>
</html>

mybooksproject/mybooksapp/templates/mybooksapp/update_book_def.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'mybooksapp/style.css' %}">
    <title>Buch bearbeitem</title>
</head>
<body>

    <div class='row justify-content-md-center p-2 mt-5'>
    <div class="col-lg-10 p-4 bg-white rounded shadow-sm">

        <form action="{% url 'mybooksapp:update_book' book.id %}" method="POST">
        <div class="form-group">
            {% csrf_token %}
            <label for="book_title">Titel</label>
            <input class="form-control" type="text" name="book_title" id="book_title" value="{{book.title}}"><br>

            <label for="book_author">Autor</label>
            <input class="form-control" type="text" name="book_author" id="book_author" value="{{book.author}}"><br>

            <label for="book_content">Inhalt</label>
            <input class="form-control" type="text" name="book_content" id="book_content" value="{{book.content}}"><br>

            <label for="book_rating">Bewertung</label>
            <input class="form-control" type="number" name="book_rating" id="book_rating" value="{{book.rating}}"><br>

            <label for="book_done">Gelesen</label>
            <input class="form-check" type="checkbox" name="book_done" id="book_done" value="{{book.done}}" {% if book.done %}checked{% endif %}><br>

            <label for="book_price">Preis</label>
            <input class="form-control" type="number" step="0.01" name="book_price" id="book_price" value="{{book.price}}"><br>

            <label for="book_cover">Cover</label>
            <input class="form-control" type="text" name="book_cover" id="book_cover" value="{{book.cover}}"><br>

            <label for="book_booklist">Liste</label>
            <select class="form-control" name="book_booklist" id="book_booklist">
                {% for liste in listen %}
                    <option value="{{liste.id}}" {% if liste == book.liste %}selected{% endif %}>{{liste.name}}</option> 
                {% endfor %}  
            </select><br>

            <label for="book_genre">Genre</label>
            <select class="form-control" name="book_genre" id="book_genre">
                {% for genre in genres %}
                    <option value="{{genre.id}}" {% if genre == book.genre %}selected{% endif %}>{{genre.name}}</option> 
                {% endfor %}  
            </select><br>

            <div class="input-group">
                <input class="btn" type="submit" value="Speichern">
            </div>
        </div>
        </form>

    </div>
    </div>

</body>
</html>